# Generated by Django 5.0 on 2025-06-20 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("level", models.SmallIntegerField(help_text="Чем меньше — тем выше")),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "division_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("DEPARTMENT", "Департамент"),
                            ("MANAGEMENT", "Управление"),
                            ("OFFICE", "Отдел"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parent_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_divisions",
                        to="personnel.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Фото 3×4",
                        null=True,
                        upload_to="employee_photos/",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="personnel.division",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to Django User, if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personnel.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_LINEUP", "В строю"),
                            ("ON_DUTY", "На дежурстве"),
                            ("AFTER_DUTY", "После дежурства"),
                            ("BUSINESS_TRIP", "В командировке"),
                            ("TRAINING_ETC", "Учёба / Соревнования / Конференция"),
                            ("ON_LEAVE", "В отпуске"),
                            ("SICK_LEAVE", "На больничном"),
                            ("SECONDED_OUT", "Откомандирован"),
                            ("SECONDED_IN", "Прикомандирован"),
                        ],
                        default="IN_LINEUP",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="personnel.employee",
                    ),
                ),
                (
                    "secondment_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seconded_employees_log_entries",
                        to="personnel.division",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "Чтение всей организации"),
                            (2, "Чтение своего департамента"),
                            (3, "Чтение своего департамента + ред. своего управления"),
                            (4, "Полный доступ"),
                        ]
                    ),
                ),
                (
                    "division_assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned division for role-based access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personnel.division",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
