# Generated by Django 5.2.4 on 2025-08-01 07:29

from django.db import migrations

POSITIONS = [
    (1, "Начальник Организации"),
    (2, "Заместитель начальника Организации-1"),
    (3, "Заместитель начальника Организации-2"),
    (4, "Заместитель начальника Организации-3"),
    (5, "Заместитель начальника Организации-4"),
    (6, "Начальник Департамента"),
    (7, "Заместитель начальника Департамента-1"),
    (8, "Заместитель начальника Департамента-2"),
    (9, "Начальник Управления"),
    (10, "Заместитель начальника Управления"),
    (11, "Заместитель начальника Управления - начальник отдела"),
    (12, "Начальник отдела"),
    (13, "Старший инспектор"),
    (14, "Инспектор"),
    (15, "Старший официант"),
    (16, "Старший официант охраны"),
    (17, "Официант охраны"),
    (18, "Сотрудник 1 категории"),
    (19, "Сотрудник 2 категории"),
    (20, "Сотрудник 3 категории"),
]

def seed_positions(apps, schema_editor):
    Position = apps.get_model("personnel", "Position")
    for level, name in POSITIONS:
        Position.objects.create(level=level, name=name)

def revert_positions(apps, schema_editor):
    Position = apps.get_model("personnel", "Position")
    position_names = [name for level, name in POSITIONS]
    Position.objects.filter(name__in=position_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_positions, reverse_code=revert_positions),
    ]
