# Generated by Django 5.2.4 on 2025-08-01 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0004_employeestatuslog_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="acting_for_position",
            field=models.ForeignKey(
                blank=True,
                help_text="Position this employee is acting for (должность за счёт)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acting_employees",
                to="personnel.position",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="fired_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="hired_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="division_type_assignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPANY", "Company"),
                    ("DEPARTMENT", "Департамент"),
                    ("MANAGEMENT", "Управление"),
                    ("OFFICE", "Отдел"),
                ],
                help_text="Type of division for Role-5 assignment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="include_child_divisions",
            field=models.BooleanField(
                default=True,
                help_text="For Role-5: whether access includes child divisions",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SECONDMENT", "Secondment"),
                            ("STATUS_UPDATE", "Status Update"),
                            ("RETURN_REQUEST", "Return Request"),
                            ("VACANCY_CREATED", "Vacancy Created"),
                            ("TRANSFER", "Transfer"),
                            ("ESCALATION", "Escalation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "related_model",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonnelReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("file", models.FileField(upload_to="personnel_reports/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("DAILY", "Daily"), ("PERIOD", "Period")],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personnel.division",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecondmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_secondments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondment_requests",
                        to="personnel.employee",
                    ),
                ),
                (
                    "from_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_secondments",
                        to="personnel.division",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_secondments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_secondments",
                        to="personnel.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Количество по штату"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_units",
                        to="personnel.division",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personnel.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staffing Unit",
                "verbose_name_plural": "Staffing Units",
                "unique_together": {("division", "position")},
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vacancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staffing_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="personnel.staffingunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("STATUS_CHANGE", "Status Change"),
                            ("TRANSFER", "Transfer"),
                            ("SECONDMENT", "Secondment"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("REPORT_GENERATED", "Report Generated"),
                            ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=50, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "user"],
                        name="personnel_a_timesta_504cad_idx",
                    ),
                    models.Index(
                        fields=["operation"], name="personnel_a_operati_7a8f63_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DivisionStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("update_date", models.DateField()),
                ("is_updated", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="personnel.division",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-update_date", "division__name"],
                "unique_together": {("division", "update_date")},
            },
        ),
    ]
