# Generated by Django 5.2.4 on 2025-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_employee_acting_for_position_employee_fired_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeestatuslog",
            name="is_auto_copied",
            field=models.BooleanField(
                default=False,
                help_text="True if this status was automatically copied from the previous day.",
            ),
        ),
    ]
