# Generated by Django 5.2.4 on 2025-08-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0007_remove_auditlog_user_alter_division_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
