# Generated by Django 5.2.4 on 2025-10-26 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("divisions", "0001_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("APPROVED", "Одобрено"),
                            ("REJECTED", "Отклонено"),
                            ("CANCELLED", "Отменено"),
                            ("RETURNED", "Возвращен"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="Дата начала")),
                (
                    "date_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Причина прикомандирования")),
                (
                    "return_requested",
                    models.BooleanField(default=False, verbose_name="Запрошен возврат"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_secondments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Одобрил",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondment_requests",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "from_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_secondments",
                        to="divisions.division",
                        verbose_name="Из подразделения",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_secondments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Запросил",
                    ),
                ),
                (
                    "return_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Возврат одобрил",
                    ),
                ),
                (
                    "return_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_returns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Возврат запросил",
                    ),
                ),
                (
                    "to_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_secondments",
                        to="divisions.division",
                        verbose_name="В подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на прикомандирование",
                "verbose_name_plural": "Запросы на прикомандирование",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "date_from"],
                        name="secondments_status_c47b48_idx",
                    ),
                    models.Index(
                        fields=["employee", "status"],
                        name="secondments_employe_05e358_idx",
                    ),
                ],
            },
        ),
    ]
