# Generated by Django 5.2.4 on 2025-10-26 10:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("divisions", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Просмотр расхода всей организации (без редактирования)",
                            ),
                            (
                                2,
                                "Просмотр расхода только своего департамента (без редактирования)",
                            ),
                            (
                                3,
                                "Просмотр департамента + редактирование только своего управления",
                            ),
                            (4, "Полный доступ ко всем функциям"),
                            (5, "Кадровый администратор подразделения"),
                            (
                                6,
                                "Просмотр департамента + редактирование только своего отдела",
                            ),
                        ],
                        verbose_name="Роль",
                    ),
                ),
                (
                    "include_child_divisions",
                    models.BooleanField(
                        default=True,
                        help_text="Для Роли-5: включает ли доступ дочерние подразделения",
                        verbose_name="Включать дочерние подразделения",
                    ),
                ),
                (
                    "division_type_assignment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPANY", "Company"),
                            ("DEPARTMENT", "Департамент"),
                            ("MANAGEMENT", "Управление"),
                            ("OFFICE", "Отдел"),
                        ],
                        help_text="Ограничение по типу подразделения для Роли-5",
                        max_length=20,
                        null=True,
                        verbose_name="Тип подразделения для Роли-5",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "division_assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Подразделение для ролевого доступа",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="divisions.division",
                        verbose_name="Назначенное подразделение",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
