# Generated by Django 5.2.4 on 2025-10-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Уникальный код подразделения",
                        max_length=50,
                        verbose_name="Код подразделения",
                    ),
                ),
                (
                    "division_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("DEPARTMENT", "Департамент"),
                            ("MANAGEMENT", "Управление"),
                            ("OFFICE", "Отдел"),
                        ],
                        max_length=20,
                        verbose_name="Тип подразделения",
                    ),
                ),
                (
                    "hierarchy_variant",
                    models.CharField(
                        choices=[
                            (
                                "VARIANT_1",
                                "Компания → Департаменты → Управления → Отделы",
                            ),
                            ("VARIANT_2", "Компания → Управления → Отделы"),
                            ("VARIANT_3", "Компания → Отделы"),
                        ],
                        default="VARIANT_1",
                        help_text="Вариант организационной иерархии для данной структуры",
                        max_length=20,
                        verbose_name="Вариант иерархии",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о подразделении",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="Контактная информация"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "head_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_divisions",
                        to="dictionaries.position",
                        verbose_name="Должность руководителя",
                    ),
                ),
                (
                    "parent_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_divisions",
                        to="divisions.division",
                        verbose_name="Родительское подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ["division_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["division_type", "parent_division"],
                        name="divisions_d_divisio_12a30d_idx",
                    ),
                    models.Index(fields=["code"], name="divisions_d_code_6cc01b_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("code__isnull", False),
                            models.Q(("code", ""), _negated=True),
                        ),
                        fields=("code", "parent_division"),
                        name="unique_code_per_parent",
                    )
                ],
            },
        ),
    ]
