# Generated by Django 5.2.4 on 2025-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
