# Generated by Django 5.2.4 on 2025-10-26 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("divisions", "0001_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DivisionStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_date",
                    models.DateField(db_index=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_updated",
                    models.BooleanField(
                        default=False,
                        help_text="Флаг обновления статусов",
                        verbose_name="Обновлено",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="divisions.division",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обновление статусов подразделения",
                "verbose_name_plural": "Обновления статусов подразделений",
                "ordering": ["-update_date", "division__name"],
                "indexes": [
                    models.Index(
                        fields=["update_date", "is_updated"],
                        name="statuses_di_update__5a498a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("division", "update_date"),
                        name="unique_division_update_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ON_DUTY_SCHEDULED", "В строю"),
                            ("ON_DUTY_ACTUAL", "На дежурстве"),
                            ("AFTER_DUTY", "После дежурства"),
                            ("BUSINESS_TRIP", "В командировке"),
                            ("TRAINING_ETC", "Учёба/соревнования/конференция"),
                            ("ON_LEAVE", "В отпуске"),
                            ("SICK_LEAVE", "На больничном"),
                            ("SECONDED_OUT", "Откомандирован"),
                            ("SECONDED_IN", "Прикомандирован"),
                        ],
                        default="ON_DUTY_SCHEDULED",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(db_index=True, verbose_name="Дата начала"),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_auto_copied",
                    models.BooleanField(
                        default=False,
                        help_text="True если статус был автоматически скопирован с предыдущего дня",
                        verbose_name="Автоматически скопировано",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "secondment_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seconded_employees_log_entries",
                        to="divisions.division",
                        verbose_name="Подразделение прикомандирования",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_status_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обновлено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал статусов",
                "verbose_name_plural": "Журналы статусов",
                "ordering": ["-date_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date_from", "date_to"],
                        name="statuses_em_employe_cbd379_idx",
                    ),
                    models.Index(
                        fields=["status", "date_from"],
                        name="statuses_em_status_b89b07_idx",
                    ),
                    models.Index(
                        fields=["is_auto_copied"], name="statuses_em_is_auto_767967_idx"
                    ),
                ],
            },
        ),
    ]
