# Generated by Django 5.2.4 on 2025-10-26 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0001_initial"),
        ("divisions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Фото 3×4",
                        null=True,
                        upload_to="employee_photos/%Y/%m/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Табельный номер",
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата приёма на работу"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные сотрудники считаются уволенными",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "fired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Контактный телефон"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Контактный email"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="divisions.division",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.position",
                        verbose_name="Должность",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Связь с пользователем Django, если применимо",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="Дата перевода")),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Основание перевода"),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер приказа"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_logs",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "from_division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from",
                        to="divisions.division",
                        verbose_name="Из подразделения",
                    ),
                ),
                (
                    "from_position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from_position",
                        to="dictionaries.position",
                        verbose_name="С должности",
                    ),
                ),
                (
                    "to_division",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="divisions.division",
                        verbose_name="В подразделение",
                    ),
                ),
                (
                    "to_position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to_position",
                        to="dictionaries.position",
                        verbose_name="На должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал переводов",
                "verbose_name_plural": "Журнал переводов",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Количество штатных единиц",
                        verbose_name="Количество по штату",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_staffing_units",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffing_units",
                        to="divisions.division",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionaries.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Штатная единица",
                "verbose_name_plural": "Штатные единицы",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название вакансии"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Требования"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Высокий"), (2, "Средний"), (3, "Низкий")],
                        default=2,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата закрытия"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Закрыто пользователем",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано пользователем",
                    ),
                ),
                (
                    "staffing_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="employees.staffingunit",
                        verbose_name="Штатная единица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_active", "division"], name="employees_e_is_acti_760920_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="employees_e_last_na_99a4c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_number"], name="employees_e_employe_e7cf1b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffingunit",
            constraint=models.UniqueConstraint(
                fields=("division", "position"),
                name="unique_staffing_per_division_position",
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["is_active", "priority"], name="employees_v_is_acti_8d9cdd_idx"
            ),
        ),
    ]
