# Generated by Django 5.2.4 on 2025-08-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0002_seed_positions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Просмотр всей организации (без редактирования)"),
                    (2, "Просмотр своего департамента (без редактирования)"),
                    (3, "Редактирование своего управления"),
                    (4, "Полный доступ (администратор)"),
                    (5, "Кадровый администратор подразделения"),
                    (6, "Редактирование своего отдела"),
                ]
            ),
        ),
    ]
