# Generated by Django 5.2.4 on 2025-08-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0006_employeestatuslog_is_auto_copied"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
