# Generated by Django 5.2.4 on 2025-08-05 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personnel",
            "0008_remove_notification_recipient_alter_division_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={"verbose_name": "Division", "verbose_name_plural": "Divisions"},
        ),
        migrations.AlterModelOptions(
            name="divisionstatusupdate",
            options={
                "ordering": ["-update_date", "division__name"],
                "verbose_name": "Division Status Update",
                "verbose_name_plural": "Division Status Updates",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee", "verbose_name_plural": "Employees"},
        ),
        migrations.AlterModelOptions(
            name="employeestatuslog",
            options={
                "ordering": ["-date_from", "-id"],
                "verbose_name": "Employee Status Log",
                "verbose_name_plural": "Employee Status Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="personnelreport",
            options={
                "ordering": ["-report_date", "-created_at"],
                "verbose_name": "Personnel Report",
                "verbose_name_plural": "Personnel Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
            },
        ),
        migrations.AlterModelOptions(
            name="secondmentrequest",
            options={
                "verbose_name": "Secondment Request",
                "verbose_name_plural": "Secondment Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name": "Vacancy", "verbose_name_plural": "Vacancies"},
        ),
        migrations.AlterUniqueTogether(
            name="divisionstatusupdate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="staffingunit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="division",
            name="hierarchy_variant",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Стандартная"),
                    ("DIRECT", "Прямое подчинение"),
                    ("MIXED", "Смешанная"),
                ],
                default="STANDARD",
                help_text="Вариант иерархии для данной структуры",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="acting_for_position",
            field=models.ForeignKey(
                blank=True,
                help_text="Должность, за счёт которой действует сотрудник",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acting_employees",
                to="personnel.position",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фото 3×4 (stored in year/month folders)",
                null=True,
                upload_to="employee_photos/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Связь с пользователем Django, если применимо",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_DUTY_SCHEDULED", "В строю"),
                    ("ON_DUTY", "На дежурстве"),
                    ("AFTER_DUTY", "После дежурства"),
                    ("BUSINESS_TRIP", "В командировке"),
                    ("TRAINING_ETC", "Учёба / Соревнования / Конференция"),
                    ("ON_LEAVE", "В отпуске"),
                    ("SICK_LEAVE", "На больничном"),
                    ("SECONDED_OUT", "Откомандирован"),
                    ("SECONDED_IN", "Прикомандирован"),
                ],
                default="ON_DUTY_SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="division_type_assignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPANY", "Company"),
                    ("DEPARTMENT", "Департамент"),
                    ("MANAGEMENT", "Управление"),
                    ("OFFICE", "Отдел"),
                ],
                help_text="Type of division for Role‑5 assignment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="include_child_divisions",
            field=models.BooleanField(
                default=True,
                help_text="For Role‑5: whether access includes child divisions",
            ),
        ),
        migrations.AddIndex(
            model_name="employeestatuslog",
            index=models.Index(
                fields=["employee", "date_from", "date_to"],
                name="personnel_e_employe_3047fc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="divisionstatusupdate",
            constraint=models.UniqueConstraint(
                fields=("division", "update_date"), name="unique_division_update_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffingunit",
            constraint=models.UniqueConstraint(
                fields=("division", "position"),
                name="unique_staffing_per_division_position",
            ),
        ),
    ]
