# Generated by Django 5.2.4 on 2025-08-06 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_alter_division_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeTransferLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField(verbose_name="Дата перевода")),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Основание перевода"),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер приказа"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Журнал переводов",
                "verbose_name_plural": "Журнал переводов",
                "ordering": ["-transfer_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название правила"),
                ),
                (
                    "time_threshold",
                    models.TimeField(
                        help_text="Время, после которого срабатывает эскалация",
                        verbose_name="Временной порог",
                    ),
                ),
                (
                    "notification_roles",
                    models.JSONField(
                        default=list,
                        help_text="Список ролей, которые получат уведомление",
                        verbose_name="Роли для уведомления",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "auto_copy_statuses",
                    models.BooleanField(
                        default=False,
                        help_text="Копировать статусы с предыдущего дня при срабатывании",
                        verbose_name="Автоматически копировать статусы",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Правило эскалации",
                "verbose_name_plural": "Правила эскалации",
                "ordering": ["time_threshold"],
            },
        ),
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["division_type", "name"],
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.AlterModelOptions(
            name="divisionstatusupdate",
            options={
                "ordering": ["-update_date", "division__name"],
                "verbose_name": "Обновление статусов подразделения",
                "verbose_name_plural": "Обновления статусов подразделений",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["position__level", "full_name"],
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.AlterModelOptions(
            name="employeestatuslog",
            options={
                "ordering": ["-date_from", "-id"],
                "verbose_name": "Журнал статусов",
                "verbose_name_plural": "Журналы статусов",
            },
        ),
        migrations.AlterModelOptions(
            name="personnelreport",
            options={
                "ordering": ["-report_date", "-created_at"],
                "verbose_name": "Отчет по личному составу",
                "verbose_name_plural": "Отчеты по личному составу",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
            },
        ),
        migrations.AlterModelOptions(
            name="secondmentrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запрос на прикомандирование",
                "verbose_name_plural": "Запросы на прикомандирование",
            },
        ),
        migrations.AlterModelOptions(
            name="staffingunit",
            options={
                "verbose_name": "Штатная единица",
                "verbose_name_plural": "Штатные единицы",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["priority", "-created_at"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.AddField(
            model_name="division",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Уникальный код подразделения",
                max_length=50,
                verbose_name="Код подразделения",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="contact_info",
            field=models.TextField(blank=True, verbose_name="Контактная информация"),
        ),
        migrations.AddField(
            model_name="division",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="division",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная информация о подразделении",
                verbose_name="Описание",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="head_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_divisions",
                to="personnel.position",
                verbose_name="Должность руководителя",
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Контактный email"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Контактный телефон"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Табельный номер"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примечания"),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employeestatuslog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employeestatuslog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_status_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновлено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="personnelreport",
            name="file_format",
            field=models.CharField(
                choices=[("docx", "Word"), ("xlsx", "Excel"), ("pdf", "PDF")],
                default="docx",
                max_length=10,
                verbose_name="Формат файла",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание должности"),
        ),
        migrations.AddField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Неактивные должности не отображаются при выборе",
                verbose_name="Активна",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="secondmentrequest",
            name="return_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_returns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Возврат одобрил",
            ),
        ),
        migrations.AddField(
            model_name="secondmentrequest",
            name="return_requested",
            field=models.BooleanField(default=False, verbose_name="Запрошен возврат"),
        ),
        migrations.AddField(
            model_name="secondmentrequest",
            name="return_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_returns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Возврат запросил",
            ),
        ),
        migrations.AddField(
            model_name="staffingunit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_staffing_units",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="division",
            name="division_type",
            field=models.CharField(
                choices=[
                    ("COMPANY", "Company"),
                    ("DEPARTMENT", "Департамент"),
                    ("MANAGEMENT", "Управление"),
                    ("OFFICE", "Отдел"),
                ],
                max_length=20,
                verbose_name="Тип подразделения",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="hierarchy_variant",
            field=models.CharField(
                choices=[
                    ("VARIANT_1", "Компания → Департаменты → Управления → Отделы"),
                    ("VARIANT_2", "Компания → Управления → Отделы"),
                    ("VARIANT_3", "Компания → Отделы"),
                ],
                default="VARIANT_1",
                help_text="Вариант организационной иерархии для данной структуры",
                max_length=20,
                verbose_name="Вариант иерархии",
            ),
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="division",
            name="parent_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_divisions",
                to="personnel.division",
                verbose_name="Родительское подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="divisionstatusupdate",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_updates",
                to="personnel.division",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="divisionstatusupdate",
            name="is_updated",
            field=models.BooleanField(
                default=False,
                help_text="Флаг обновления статусов",
                verbose_name="Обновлено",
            ),
        ),
        migrations.AlterField(
            model_name="divisionstatusupdate",
            name="update_date",
            field=models.DateField(db_index=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="divisionstatusupdate",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время обновления"
            ),
        ),
        migrations.AlterField(
            model_name="divisionstatusupdate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Обновлено пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="acting_for_position",
            field=models.ForeignKey(
                blank=True,
                help_text="Должность, за счёт которой действует сотрудник",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acting_employees",
                to="personnel.position",
                verbose_name="Должность за счёт",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="personnel.division",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fired_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата увольнения"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hired_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата приёма на работу"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Неактивные сотрудники считаются уволенными",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фото 3×4",
                null=True,
                upload_to="employee_photos/%Y/%m/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="personnel.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Связь с пользователем Django, если применимо",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_status_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="date_from",
            field=models.DateField(db_index=True, verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="date_to",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="personnel.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="is_auto_copied",
            field=models.BooleanField(
                default=False,
                help_text="True если статус был автоматически скопирован с предыдущего дня",
                verbose_name="Автоматически скопировано",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="secondment_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seconded_employees_log_entries",
                to="personnel.division",
                verbose_name="Подразделение прикомандирования",
            ),
        ),
        migrations.AlterField(
            model_name="employeestatuslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_DUTY_SCHEDULED", "В строю"),
                    ("ON_DUTY", "На дежурстве"),
                    ("AFTER_DUTY", "После дежурства"),
                    ("BUSINESS_TRIP", "В командировке"),
                    ("TRAINING_ETC", "Учёба/соревнования/конференция"),
                    ("ON_LEAVE", "В отпуске"),
                    ("SICK_LEAVE", "На больничном"),
                    ("SECONDED_OUT", "Откомандирован"),
                    ("SECONDED_IN", "Прикомандирован"),
                ],
                default="ON_DUTY_SCHEDULED",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="date_from",
            field=models.DateField(verbose_name="Дата начала периода"),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="date_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания периода"
            ),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="personnel.division",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="file",
            field=models.FileField(
                upload_to="personnel_reports/%Y/%m/%d/", verbose_name="Файл отчета"
            ),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="report_date",
            field=models.DateField(db_index=True, verbose_name="Дата отчета"),
        ),
        migrations.AlterField(
            model_name="personnelreport",
            name="report_type",
            field=models.CharField(
                choices=[("DAILY", "На один день"), ("PERIOD", "За период")],
                default="DAILY",
                max_length=20,
                verbose_name="Тип отчета",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="level",
            field=models.SmallIntegerField(
                help_text="Чем меньше число, тем выше должность", verbose_name="Уровень"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название должности"),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_secondments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Одобрил",
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="date_from",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="date_to",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secondment_requests",
                to="personnel.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="from_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_secondments",
                to="personnel.division",
                verbose_name="Из подразделения",
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="reason",
            field=models.TextField(verbose_name="Причина прикомандирования"),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_secondments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Запросил",
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Ожидает"),
                    ("APPROVED", "Одобрено"),
                    ("REJECTED", "Отклонено"),
                    ("CANCELLED", "Отменено"),
                    ("RETURNED", "Возвращен"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="secondmentrequest",
            name="to_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_secondments",
                to="personnel.division",
                verbose_name="В подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="staffingunit",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffing_units",
                to="personnel.division",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="staffingunit",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="personnel.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="staffingunit",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Количество штатных единиц",
                verbose_name="Количество по штату",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="division_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Подразделение для ролевого доступа",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="personnel.division",
                verbose_name="Назначенное подразделение",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="division_type_assignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMPANY", "Company"),
                    ("DEPARTMENT", "Департамент"),
                    ("MANAGEMENT", "Управление"),
                    ("OFFICE", "Отдел"),
                ],
                help_text="Ограничение по типу подразделения для Роли-5",
                max_length=20,
                null=True,
                verbose_name="Тип подразделения для Роли-5",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="include_child_divisions",
            field=models.BooleanField(
                default=True,
                help_text="Для Роли-5: включает ли доступ дочерние подразделения",
                verbose_name="Включать дочерние подразделения",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.IntegerField(
                choices=[
                    (1, "Просмотр расхода всей организации (без редактирования)"),
                    (
                        2,
                        "Просмотр расхода только своего департамента (без редактирования)",
                    ),
                    (
                        3,
                        "Просмотр департамента + редактирование только своего управления",
                    ),
                    (4, "Полный доступ ко всем функциям"),
                    (5, "Кадровый администратор подразделения"),
                    (6, "Просмотр департамента + редактирование только своего отдела"),
                ],
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата закрытия"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_vacancies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Закрыто пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_vacancies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Активна"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Высокий"), (2, "Средний"), (3, "Низкий")],
                default=2,
                verbose_name="Приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(blank=True, verbose_name="Требования"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="staffing_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="personnel.staffingunit",
                verbose_name="Штатная единица",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название вакансии"),
        ),
        migrations.AddIndex(
            model_name="division",
            index=models.Index(
                fields=["division_type", "parent_division"],
                name="personnel_d_divisio_80fe73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="division",
            index=models.Index(fields=["code"], name="personnel_d_code_4fe0ba_idx"),
        ),
        migrations.AddIndex(
            model_name="divisionstatusupdate",
            index=models.Index(
                fields=["update_date", "is_updated"],
                name="personnel_d_update__831ebc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["is_active", "division"], name="personnel_e_is_acti_44eb68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["full_name"], name="personnel_e_full_na_07439c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["employee_number"], name="personnel_e_employe_9b1503_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeestatuslog",
            index=models.Index(
                fields=["status", "date_from"], name="personnel_e_status_1a043c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeestatuslog",
            index=models.Index(
                fields=["is_auto_copied"], name="personnel_e_is_auto_b7f0a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personnelreport",
            index=models.Index(
                fields=["report_date", "division"],
                name="personnel_p_report__6b1c9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personnelreport",
            index=models.Index(
                fields=["report_type", "created_at"],
                name="personnel_p_report__dcd5f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["level"], name="personnel_p_level_bb1e59_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["is_active"], name="personnel_p_is_acti_8c34cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="secondmentrequest",
            index=models.Index(
                fields=["status", "date_from"], name="personnel_s_status_fae932_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="secondmentrequest",
            index=models.Index(
                fields=["employee", "status"], name="personnel_s_employe_913f4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["is_active", "priority"], name="personnel_v_is_acti_f1534e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("code__isnull", False), models.Q(("code", ""), _negated=True)
                ),
                fields=("code", "parent_division"),
                name="unique_code_per_parent",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано пользователем",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_logs",
                to="personnel.employee",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="from_division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from",
                to="personnel.division",
                verbose_name="Из подразделения",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="from_position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from_position",
                to="personnel.position",
                verbose_name="С должности",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="to_division",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_to",
                to="personnel.division",
                verbose_name="В подразделение",
            ),
        ),
        migrations.AddField(
            model_name="employeetransferlog",
            name="to_position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_to_position",
                to="personnel.position",
                verbose_name="На должность",
            ),
        ),
    ]
