# Generated by Django 5.2.4 on 2025-08-05 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_session_id"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("STATUS_CHANGE", "Status Change"),
                    ("TRANSFER", "Transfer"),
                    ("SECONDMENT", "Secondment"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("REPORT_GENERATED", "Report Generated"),
                    ("UNAUTHORIZED_ACCESS", "Unauthorized Access"),
                    ("ESCALATION", "Escalation"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="audit_audit_content_4c2ead_idx",
            ),
        ),
    ]
