# Generated by Django 5.2.4 on 2025-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DismissalReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Причина увольнения",
                "verbose_name_plural": "Причины увольнения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Типы документов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EducationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип образования",
                "verbose_name_plural": "Типы образования",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StatusType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Тип статуса",
                "verbose_name_plural": "Типы статусов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Ключ"),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройка системы",
                "verbose_name_plural": "Настройки системы",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TransferReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Причина перевода",
                "verbose_name_plural": "Причины перевода",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VacancyReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Причина открытия вакансии",
                "verbose_name_plural": "Причины открытия вакансии",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название должности"),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        help_text="Чем меньше число, тем выше должность",
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание должности"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Неактивные должности не отображаются при выборе",
                        verbose_name="Активна",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["level", "name"],
                "indexes": [
                    models.Index(fields=["level"], name="dictionarie_level_43d780_idx"),
                    models.Index(
                        fields=["is_active"], name="dictionarie_is_acti_baa85f_idx"
                    ),
                ],
            },
        ),
    ]
